################################################################################
# MIT License
#
# Copyright (c) 2018 Aludirk Wong <aludirkwong@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
################################################################################

version: "3.5"
services:
  abci1:
    build: ./abci
    image: abci:latest
    container_name: abci1
    command: run "${MAIN_GO}"
    expose:
      - 46658
    volumes:
      - type: bind
        source: "${SOURCE}"
        target: /abci
  tendermint1:
    build: ./tendermint
    image: tendermint:0.19.3
    container_name: tendermint1
    depends_on:
      - abci1
    expose:
      - 46656
    ports:
      - 46661:46657
    volumes:
      - type: bind
        source: ./tendermint/node_1
        target: /tendermint
  abci2:
    build: ./abci
    image: abci:latest
    container_name: abci2
    command: run "${MAIN_GO}"
    expose:
      - 46658
    volumes:
      - type: bind
        source: "${SOURCE}"
        target: /abci
  tendermint2:
    build: ./tendermint
    image: tendermint:0.19.3
    container_name: tendermint2
    depends_on:
      - abci2
    expose:
      - 46656
    ports:
      - 46662:46657
    volumes:
      - type: bind
        source: ./tendermint/node_2
        target: /tendermint
  abci3:
    build: ./abci
    image: abci:latest
    container_name: abci3
    command: run "${MAIN_GO}"
    expose:
      - 46658
    volumes:
      - type: bind
        source: "${SOURCE}"
        target: /abci
  tendermint3:
    build: ./tendermint
    image: tendermint:0.19.3
    container_name: tendermint3
    depends_on:
      - abci3
    expose:
      - 46656
    ports:
      - 46663:46657
    volumes:
      - type: bind
        source: ./tendermint/node_3
        target: /tendermint
  abci4:
    build: ./abci
    image: abci:latest
    container_name: abci4
    command: run "${MAIN_GO}"
    expose:
      - 46658
    volumes:
      - type: bind
        source: "${SOURCE}"
        target: /abci
  tendermint4:
    build: ./tendermint
    image: tendermint:0.19.3
    container_name: tendermint4
    depends_on:
      - abci4
    expose:
      - 46656
    ports:
      - 46664:46657
    volumes:
      - type: bind
        source: ./tendermint/node_4
        target: /tendermint
